# Generated by Django 4.2.13 on 2024-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monumetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('seller_type', models.CharField(max_length=255)),
                ('date_first_added', models.DateField(auto_now_add=True)),
                ('ad_platform', models.CharField(default='monumetric', max_length=50)),
            ],
            options={
                'unique_together': {('domain', 'ad_platform')},
            },
        ),
        migrations.CreateModel(
            name='Mediavine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('seller_type', models.CharField(max_length=255)),
                ('date_first_added', models.DateField(auto_now_add=True)),
                ('ad_platform', models.CharField(default='mediavine', max_length=50)),
            ],
            options={
                'unique_together': {('domain', 'ad_platform')},
            },
        ),
        migrations.CreateModel(
            name='AdThrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('seller_type', models.CharField(max_length=255)),
                ('date_first_added', models.DateField(auto_now_add=True)),
                ('ad_platform', models.CharField(default='adthrive', max_length=50)),
            ],
            options={
                'unique_together': {('domain', 'ad_platform')},
            },
        ),
    ]
