# Generated by Django 4.2.13 on 2024-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adthrive',
            name='ad_platform',
            field=models.CharField(default='adthrive', max_length=100),
        ),
        migrations.AlterField(
            model_name='adthrive',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adthrive',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adthrive',
            name='seller_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adthrive',
            name='seller_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavine',
            name='ad_platform',
            field=models.CharField(default='mediavine', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavine',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavine',
            name='seller_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediavine',
            name='seller_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monumetric',
            name='ad_platform',
            field=models.CharField(default='monumetric', max_length=100),
        ),
        migrations.AlterField(
            model_name='monumetric',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monumetric',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monumetric',
            name='seller_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monumetric',
            name='seller_type',
            field=models.CharField(max_length=100),
        ),
    ]
